<?php
const HTTP_HOST = "http://localhost:8080";
const DIRECTORIO_VISTAS = "app/View/";

const DIRECTORIO_VISTAS_FRONTEND= DIRECTORIO_VISTAS . "frontend/";
const DIRECTORIO_TEMPLATE_FRONTEND =DIRECTORIO_VISTAS_FRONTEND ."template/";
const DIRECTORIO_CSS_FRONTEND = DIRECTORIO_TEMPLATE_FRONTEND."css/";
const DIRECTORIO_IMG_FRONTEND = DIRECTORIO_TEMPLATE_FRONTEND."img/";
const DIRECTORIO_JS_FRONTEND = DIRECTORIO_TEMPLATE_FRONTEND."js/";

const DIRECTORIO_VISTAS_BACKEND= DIRECTORIO_VISTAS . "backend/";
const DIRECTORIO_TEMPLATE_BACKEND= DIRECTORIO_VISTAS_BACKEND."template/";
const DIRECTORIO_CSS_BACKEND = "/app/View/backend/template/css/";
const DIRECTORIO_IMG_BACKEND = "/app/View/backend/template/img/";
const DIRECTORIO_JS_BACKEND = "/app/View/backend/template/js/";


const USUARIO_BASE_DATOS = "matomas";
